apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
    {
        "auths": {
            {{- if not .Values.authIgnore }}
            {{- range $i, $val := .Values.dockerconfig.auths }}
            {{ $val.registry | quote }}: {
                "auth": {{ printf "%s:%s" $val.username $val.password | b64enc | quote }}
            }{{- if (lt $i (sub ($.Values.dockerconfig.auths | len) 1)) }},{{- end }}
            {{- end }}
            {{- end }}
        },
        "max-concurrent-uploads": 1,
        "max-concurrent-downloads": 1
    }
