apiVersion: v1
kind: Service
metadata:
  name: {{ template "master-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
spec:
  ports:
    - port: {{ .Values.Master.ServicePort }}
      targetPort: {{ .Values.Master.ContainerPort }}
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "webui-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
spec:
  ports:
    - port: {{ .Values.WebUi.ServicePort }}
      targetPort: {{ .Values.WebUi.ContainerPort }}
      name: "web-port"
    - port: {{ .Values.Master.ServicePort }}
      targetPort: {{ .Values.Master.ServicePort }}
      name: "spark-port"
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
  type: {{ .Values.Master.ServiceType }}
---
apiVersion: {{ template "deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "master-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
spec:
  replicas: {{ default 1 .Values.Master.Replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
    spec:
      initContainers:
        - name: {{ .Release.Name }}-spark-init
          image: "busybox:latest"
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          args:
            - "-c"
            - |-
              cat /data/reverseproxy-vhosts-configmap/http80-{{ .Release.Name }}.sparkvagrant.cloud.conf > /data/reverseproxy-vhosts/http80-{{ .Release.Name }}.sparkvagrant.cloud.conf
              cat /data/reverseproxy-vhosts-configmap/https443-{{ .Release.Name }}.sparkvagrant.cloud.conf > /data/reverseproxy-vhosts/https443-{{ .Release.Name }}.sparkvagrant.cloud.conf
          env: []
          workingDir: /data
          volumeMounts:
            - name: host-vhosts
              mountPath: /data/reverseproxy-vhosts
            - name: config-reverseproxy-vhosts
              mountPath: /data/reverseproxy-vhosts-configmap
      containers:
        - name: {{ template "master-fullname" . }}
          image: "{{ .Values.Master.Image }}:{{ .Values.Master.ImageTag }}"
          command: ["/bin/sh","-c"]
          args: ["echo $(hostname -i) {{ template "master-fullname" . }} >> /etc/hosts; {{ .Values.Spark.Path }}/bin/spark-class org.apache.spark.deploy.master.Master"]
#          lifecycle:
#            preStop:
#              exec:
#                command:
#                  - "/bin/sh"
#                  - "-c"
#                  - |-
#                    rm -f  /data/reverseproxy-vhosts/http80-{{ .Release.Name }}.sparkvagrant.cloud.conf
#                    rm -f  /data/reverseproxy-vhosts/https443-{{ .Release.Name }}.sparkvagrant.cloud.conf
          ports:
            - containerPort: {{ .Values.Master.ContainerPort }}
              hostPort: {{ .Values.Master.ContainerPort }}
              protocol: TCP
              name: spark-7077
            - containerPort: {{ .Values.WebUi.ContainerPort }}
          resources:
            requests:
              cpu: "{{ .Values.Master.Cpu }}"
              memory: "{{ .Values.Master.Memory }}"
          volumeMounts:
            - name: spark-dags
              mountPath: /var/www/spark-big-data-development-kit/getting-started-spark-app/dags
            - name: spark-files
              mountPath: /var/www/spark-big-data-development-kit/getting-started-spark-app/files
            - name: host-vhosts
              mountPath: /data/reverseproxy-vhosts
          env:
          - name: SPARK_DAEMON_MEMORY
            value: {{ default "1g" .Values.Master.DaemonMemory | quote }}
          - name: SPARK_MASTER_HOST
            value: {{ template "master-fullname" . }}
          - name: SPARK_MASTER_PORT
            value: {{ .Values.Master.ServicePort | quote }}
          - name: SPARK_MASTER_WEBUI_PORT
            value: {{ .Values.WebUi.ContainerPort | quote }}
      volumes:
        - name: config-reverseproxy-vhosts
          configMap:
            name: {{ .Release.Name }}-reverseproxy-vhosts-configmap
        - name: spark-dags
          hostPath:
            path: /var/www/spark-big-data-development-kit/getting-started-spark-app/dags
            type: Directory
        - name: spark-files
          hostPath:
            path: /var/www/spark-big-data-development-kit/getting-started-spark-app/files
            type: Directory
        - name: host-vhosts
          hostPath:
            path: /data/reverseproxy/vhosts
            type: Directory
