apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    k8s-app: {{ .Release.Name | quote }}
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name | quote }}
    spec:
      containers:
        - name: {{ .Release.Name | quote }}
          image: {{ .Values.image | quote }}
          imagePullPolicy: Always
          env:
          - name: TZ
            value: 'Europe/Amsterdam'
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
              name: http-80
            - containerPort: 443
              hostPort: 443
              protocol: TCP
              name: https-443
            - containerPort: 8001
              hostPort: 8001
              protocol: TCP
              name: http-8001
            - containerPort: 8002
              hostPort: 8002
              protocol: TCP
              name: http-8002
            - containerPort: 8003
              hostPort: 8003
              protocol: TCP
              name: http-8003
            - containerPort: 8004
              hostPort: 8004
              protocol: TCP
              name: http-8004
            - containerPort: 8005
              hostPort: 8005
              protocol: TCP
              name: http-8005
          volumeMounts:
            - name: host-vhosts
              mountPath: /usr/local/apache2/conf/vhosts/
            - name: config-vhosts
              mountPath: /usr/local/apache2/conf/vhosts/000-default-reverseproxy-http80.conf
              subPath: 000-default-reverseproxy-http80.conf
            - name: config-vhosts
              mountPath: /usr/local/apache2/conf/vhosts/000-default-reverseproxy-https443.conf
              subPath: 000-default-reverseproxy-https443.conf
            - name: config-index
              mountPath: /usr/local/apache2/htdocs/ccamvagrant/index.html
              subPath: index.html
            - name: host-pki
              mountPath: /usr/local/apache2/conf/pki
      # since this pod is coming from vfnltopmobile.azurecr.io, we need to make sure the pull secret from helm template "regcred" is loaded
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: config-vhosts
          configMap:
            name: {{ .Release.Name }}-vhosts-configmap
        - name: config-index
          configMap:
            name: {{ .Release.Name }}-index
        - name: host-vhosts
          hostPath:
            # directory location on host
            path: /data/reverseproxy/vhosts
            # this field is optional
            type: Directory
        - name: host-pki
          hostPath:
            path: /vagrant/pki
            type: Directory
